name: "Haskell CI"

on:
  pull_request:
  push:
  workflow_dispatch:  # For manual triggering
  schedule:
  - cron: "3 14 15 * *"  # 14:03 on the 15th of every month (UTC)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Run tests
      run: make check test-colors.html set stress TIMEOUT=5
